//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluskMasterUpdate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blogs
    {
        public int Id { get; set; }
        public string Gorsel { get; set; }
        public string Adi { get; set; }
        public System.DateTime Tarihi { get; set; }
        public string Icerik { get; set; }
    }
}
