//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluskMasterUpdate.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FluskMasterUpdateEntities1 : DbContext
    {
        public FluskMasterUpdateEntities1()
            : base("name=FluskMasterUpdateEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blogs> Blogs { get; set; }
        public virtual DbSet<Iletisim> Iletisim { get; set; }
        public virtual DbSet<Portfolyo> Portfolyo { get; set; }
        public virtual DbSet<Referans> Referans { get; set; }
        public virtual DbSet<Slider> Slider { get; set; }
        public virtual DbSet<Uye> Uye { get; set; }
    }
}
